### ISSUE TITLE
Need GUI support for the Project

### ISSUE THREAD

**Issue by justafolk** [justafolk/AutomateBirthdayEmails.py#1]
# Description
- Need GUI support for the project using any GUI Library you like.
- Frontend

# Needs
- 3 Buttons{Name, Date of Birth, Email id}  and linked 3 input fields
- 1 Submit Button.
- 1 Button (to the bottom right side) {Upload a csv File}
- Make the following script titled > BEp.py

# Definition of Done
- All of the required items are completed.
- Approval by 1 mentor.

>P.S: PyQt5 preferred.

**Comment by voidrohit** [comment]
I am trying to make GUI for this project. May I know what does a button (Upload a CSV file) do?
(The 3 inputs are going into a csv file)

**Comment by justafolk** [comment]
> I am trying to make GUI for this project. May I know what does a button (Upload a CSV file) do?
> (The 3 inputs are going into a csv file)

Just had a idea, if the User had a long list of people, so he could just link the csv file to the program. The Upload a csv file button would just ask for the path of the csv file to be linked. '
(try to just show a example of the csv like the original Csv file in the stuff folder.)

**Comment by voidrohit** [comment]
Ok

**Comment by voidrohit** [comment]
Can you add "hacktoberfest" topic to this repository or add the "hacktoberfest-accepted" label to the PR? So that it will eligible for the Hacktoberfest 2020.
Reference: [Updated Rule](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
